### ISSUE TITLE
GitHub Action 远程打包的 Mod 没有中文字体

### ISSUE THREAD

**Issue by imgradeone** [imgradeone/DDLCModTemplate-Chinese#3]

**Comment by Dobby233Liu** [comment]
```bash
wget -O font.zip "https://drive.google.com/uc?id=1b96aSF7A6VtIh4-XuJfaEFHhVpsQZQzw&export=download"
unzip -d game/mod_assets/font/ -j -o font.zip
rm font.zip
```
试试在下载 DDLC 数据的 action 后运行这个

**Comment by imgradeone** [comment]
> ```shell
> wget -O font.zip "https://drive.google.com/uc?id=1b96aSF7A6VtIh4-XuJfaEFHhVpsQZQzw&export=download"
> unzip -d game/mod_assets/font/ -j -o font.zip
> rm font.zip
> ```
> 
> 试试在下载 DDLC 数据的 action 后运行这个

不一定要从 Google Drive 下载，我之后会考虑把字体包放到 Releases 里面

顺便可以先在你的 fork 里试一下
