### ISSUE TITLE
【公告】中文字体包即将更新

### ISSUE THREAD

**Issue by imgradeone** [imgradeone/DDLCModTemplate-Chinese#5]
# 我们即将开始更新字体包

接下来，Yuri、Natsuki、Sayori、Monika 都会获得新的专属免费商用字体。

为什么我们会选择免费商用字体？这可是开源项目啊，版权费我可承担不起。

目前 Yuri 使用的 杨任东竹石体 也可能会被更改。

本次更新将随中文模板 1.2 发布，届时请重新下载字体包。

## 字体列表

| 角色 | 英文字体 | 社区知名汉化版采用字体 | 新中文字体 |
|:----:|:----:|:----:|:----|
| Yuri | JP Hand Slanted | 默陌信笺手写体 | 寒蝉手拙体 |
| Natsuki | Ammys Handwriting | 新蒂小丸子体 | Acy手写体 |
| Sayori | Hashtag | 新蒂下午茶体 | 851手書き雑フォント |
| Monika | Journal | 新蒂绿豆体 | 新叶念体 |

如果您使用开发版模板，现在就可以下载新字体包了

## TODO

- [x] 字体挑选
- [x] 更新 README.md 和字体文件夹内相关文档
- [x] definations
- [x] 发布字体包
- [x] 修改 GitHub Actions 的 Workflow，使其下载新版字体包

**Comment by Dobby233Liu** [comment]
# 官网收集
## 热门字体
- **[新蒂小丸子体](http://sentyfont.com/maruko.htm)** - “个人非商业使用免费下载，商业使用授权由汉仪字库提供服务”，只有高级版（120元）“支持繁体”
- **[新蒂下午茶体](http://sentyfont.com/sentytea.htm)** - “个人非商业使用免费下载，商业使用授权由汉仪字库提供服务”
- **[新蒂绿豆体](http://sentyfont.com/pea.htm)** - “个人非商业使用免费，商业使用需提前取得授权”
- **[默陌信笺手写体](https://h5.m.taobao.com/awp/core/detail.htm?id=532778438587)** - 个人非商用付费（0.01元），商用授权联系旺旺
## 模板字体
- [Acy字体](https://github.com/lxfly2000/Acy-Font)
- [851](https://pm85122.onamae.jp/851fontpage.html)
- [新叶念体](https://m.bilibili.com/video/av59155445)

**Comment by imgradeone** [comment]
> * **[新蒂小丸子体](http://sentyfont.com/maruko.htm)** - “个人非商业使用免费下载，商业使用授权由汉仪字库提供服务”，只有高级版（120元）“支持繁体”
> * **[新蒂下午茶体](http://sentyfont.com/sentytea.htm)** - “个人非商业使用免费下载，商业使用授权由汉仪字库提供服务”
> * **[新蒂绿豆体](http://sentyfont.com/pea.htm)** - “个人非商业使用免费，商业使用需提前取得授权”
> * **[默陌信笺手写体](https://h5.m.taobao.com/awp/core/detail.htm?id=532778438587)** - 个人非商用付费（0.01元），商用授权联系旺旺

为避免版权纠纷，以上字体均不会被本模板采用，这些字体仅仅只是 Steam 社区里热门的中文汉化版使用的字体。

届时使用的是 **新中文字体** 这一栏的字体。

不过 **感谢标注。** @Dobby233Liu

**Comment by imgradeone** [comment]
Monika 中文字体决定！

**新叶念体**

**Comment by imgradeone** [comment]
Natsuki 中文字体决定！

Acy手写体

**Comment by imgradeone** [comment]
Sayori - 851手書き雑フォント

Yuri - 寒蝉手拙体

**Comment by lxfly2000** [comment]
acy字体能有人用我还挺意外的，本来只是个验证自制字体可行性的产物，也没考虑什么美观度的问题，默默支持一下

**Comment by imgradeone** [comment]
如果您使用开发版模板，现在就可以下载新字体包了
